### ISSUE TITLE
Not getting the expected status message (GET /)

### ISSUE THREAD

**Issue by pvunog** [regel/loudml#11]
Hi,

Trying to test loudml on earthquake dataset on ElasticSearch (https://github.com/elastic/examples/tree/master/Exploring%20Public%20Datasets/earthquakes)

I installed loudml on CentOS 7 using the rpm.
After configuration with config.yml:

-------
datasources:
- name: elastic
  type: elasticsearch
  addr: localhost:9200
  index: ncedc-earthquakes-earthquake

storage:
  path: /var/lib/loudml

logs:
  path: /var/log/loudml

server:
  listen: localhost:8077

node.name: rtce-myclust02
-------

It started fine and loudml is listening on port 8077. But the test to check the status gives:

curl -XGET http://localhost:8077/
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

So not displaying the expected  showing the node name and version number.

But rest of API seems to work:
curl -XGET http://localhost:8077/datasources
[
  {
    "addr": "localhost:9200",
    "index": "ncedc-earthquakes-earthquake",
    "name": "elastic",
    "type": "elasticsearch"
  }
]

Did I miss anything?

**Comment by osunac** [comment]
Hi,

It looks like the doc and the source are not in sync.

Please ignore the error when querying ``/``. As you noticed the rest of the API does work.

**Comment by vnyb** [comment]
`GET` on `/` will reply LoudML version

**Comment by osunac** [comment]
Fixed in release 1.2.3.
