### ISSUE TITLE
Donut implementation detail: softplus sigmas

### ISSUE THREAD

**Issue by aljabr0** [regel/loudml#110]
Hi in your implementation of the Donut algorithm the standard deviations are not derived from softplus layers (plus a non-negative epsilon) as suggested and justified by the research paper. The current implementation is based on log sigma. Since the local variations may be extremely small this can make log sigma unbounded. Do you think this should be updated?

**Comment by regel** [comment]
Hi Nicola, I've run the Softplus layers version locally but did not see an improvement. We can work on this one together if you want to contribute a first pull request.
