### ISSUE TITLE
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.

### ISSUE THREAD

**Issue by activiteOCR** [regel/loudml#111]
Hello,

I'm trying to install loudml on debian stretch from the getting started, I managed to connect to API but I had a problem when I created a model, I recovered this log:
`2019-04-16 21:53:18.788162: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
Aborted`

I read several topics about this issue [https://github.com/tensorflow/tensorflow/issues/24548](url).
After reading this post I understood my issue, indeed I'm using Virtual machine manager installed on my NAS DS918+ with this CPU model: Intel Celeron J3455 so imcompatible with AVX instruction. 

So I decided to install a Tensorflow library not compiled with AVX instruction, I recovered this library here [https://github.com/yaroslavvb/tensorflow-community-wheels/issues/98](url) before last comment.

I perform this `sudo -H pip3 install http://data.neural.cz/tensorflow-wheels/cpu-no-avx-sse4/tensorflow-1.12.0-cp35-cp35m-linux_x86_64.whl` then I checked with ` python3 -c 'import tensorflow as tf; print(tf.__version__)'` my tensorflow version, I get 1.12.0 on the std output.

In spite of this new library (not compiled with avx instruction) the problem is persistent...

Do you give me the way to solve this issue? What is the right way to install the tensorflow library suitable for my configuration? 

Thank you.

**Comment by activiteOCR** [comment]
Hello, any chance to provide a loudml docker component with tensorflow not compiled with AVX instruction???

Thank you?

**Comment by nonostar** [comment]
rm -rf /usr/lib/loudml/vendor/tensorflow*

**Comment by regel** [comment]
Agree with @nonostar. We bundle the standard TF version and apparently the TF team decided to enable AVX flags by default. As suggested the easiest way to change version is to remove the TF directory and replace it with your own PIP3 install.

**Comment by lblabr** [comment]
I'm really new to docker an loudml, could somebody be so kind to describe what exactrly to do ? after pull from dockerhub ?`

thanks in advance

Lars

**Comment by regel** [comment]
@activiteOCR 

>Hello, any chance to provide a loudml docker component with tensorflow not compiled with AVX instruction???

Yes. It is on the radar and the next official docker image will receive a -noavx tag.

**Comment by activiteOCR** [comment]
Thank you for your work, I stay tuned for the next release.

**Comment by lblabr** [comment]
i compiled tensorflow with:

bazel build --config=mkl -c opt --copt=-march=native //tensorflow/tools/pip_package:build_pip_package

**Comment by regel** [comment]
Tip: a useful resource for TF build is: https://github.com/hadim/docker-tensorflow-builder

Apparently, TF turned AVX on in r1.6. We can refer to the official Tensorflow Dockerfile(s) and compare what it was before & after r1.6

**Comment by regel** [comment]
WIP.

I'm trying to break it down step by step.

1. I'm using the official Tensorflow [Dockerfile](https://github.com/tensorflow/tensorflow/tree/r1.13/tensorflow/tools/dockerfiles) named devel-cpu.Dockerfile. Building this container gives a clean build environment. The bazel version environment variable must be changed according to the version we want to build. See: https://www.tensorflow.org/install/source

Build the container:

`docker build -f ./dockerfiles/devel-cpu.Dockerfile -t tf .`

2. Open a shell to this container. Use a volume to include the `tests` directory. Use a second volume called out, to exchange files in read/write mode.

Edit `build-cpu.sh` file, remove the avx option, remove `rm /tmp/pip` command, and run the script. This will output the wheel file in `/tmp/pip`. Save this file to the output volume for later use.

3. Use `cpu.Dockerfile` and edit this file in order to use and install the wheel file from above. This should build a base container, without AVX. I will try to push this base image to the loudml docker account and use it to release the -no-avx images of loudml containers. I want to try this last step with stretch-slim rather than Ubuntu.

4. Unit testing everything. Running and testing the new containers via CircleCI directly, or a GKE pod.

**Comment by regel** [comment]
`2019-08-10 09:47:36.876519: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA`

WIP.

A first docker container is released.

Try: `docker pull loudml/loudml:latest-devel-noavx`

This image is built and pushed by the CICD pipeline and will be updated automatically with all changes made in the `master` branch. More instructions on the docker [page](https://hub.docker.com/r/loudml/loudml)

Looking forward to your feedback before closing this issue.

**Comment by activiteOCR** [comment]
Hello, Thank you for your support, I installed latest-devel-noavx image and now I can create model, I tried with the model available under loudml.io and it works. 
But I have some question because I'm a beginner concerning docker concept, after an apt-get update I tried to install some package from the ubuntu repository like nano and I met an issue hereinafter the logs.
`root@loudml-loudml1:/etc/loudml# apt-get install nano                                                                                                                                                       
Reading package lists... Done                                                                                                                                                                               
Building dependency tree                                                                                                                                                                                    
Reading state information... Done                                                                                                                                                                           
You might want to run 'apt --fix-broken install' to correct these.                                                                                                                                          
The following packages have unmet dependencies:                                                                                                                                                             
 loudml : Depends: loudml-base (= 1.5.0.68.g4ea64ce) but it is not going to be installed                                                                                                                    
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).                                                                                                             
`
I'm meeting also a problem regarding the training but it's another topic, in my opinion and concerning AVX instruction now it's ok.

Maybe I can close the issue?
Thank you.

**Comment by regel** [comment]
Thank you for your feedback. Let’s close this issue and track the other one separately.

A very important note: if you upgrade to the new build today you will notice significant changes in the master version. No release notes yet, but the documentation has been updated. You will notice that the CLI tool moved outside the core package and now can be installed via PyPI.
