### ISSUE TITLE
install problem on centos 7

### ISSUE THREAD

**Issue by wjljack** [regel/loudml#112]
first I install python with `sudo yum install python34` command,then run
`sudo yum install loudml loudml-elastic loudml-influx`,but print error:
```
Error: Package: loudml-1.5.0-1.el7.centos.x86_64 (loudml-1.x)
           Requires: /bin/python3
Error: Package: loudml-elastic-1.4.3-1.el7.centos.x86_64 (loudml-1.x)
           Requires: loudml = 1.4.3
```
so I run command` ll /bin/ |grep python`
```
lrwxrwxrwx  1 root root          7 Jun 13  2017 python -> python2
lrwxrwxrwx  1 root root          9 Jun 13  2017 python2 -> python2.7
-rwxr-xr-x  1 root root       7136 Nov  6  2016 python2.7
-rwxr-xr-x  2 root root      11384 Mar  7 23:51 python3.4
-rwxr-xr-x  2 root root      11384 Mar  7 23:51 python3.4m
```
only found python3.4, not python3, use `ln -s python3.4 python3` not work.

**Comment by osunac** [comment]
On a CentOS 7 the Python executable is actually `/usr/bin/python3` and this should not block the installation.

In your case the real issue is that you must not install the packages `loudml-elastic` nor `loudml-influx` because they are designed for Loud ML 1.4.3 ; with the version 1.5.0 you only need `loudml-base` and `loudml`.

**Comment by fmercier-almerys** [comment]
not really even with loudml it failed even  ln -s /usr/bin/python3.4 /bin/python3 does not resolve the issue

**Comment by MaikkiTech** [comment]
I can verify this same issue with RHEL7.

Has someone found a solution for this?

**Comment by regel** [comment]
Updated the repo to migrate to python 3.6. You can rebuild (`make rpm`) the RPMs on master. View the README file to make sure your pip is installed in `/opt` before your build. And finally, run `yum install` on the new RPM file to do the install. You should see two packages: `loudml` and `loudml-base`

**Comment by regel** [comment]
@wjljack can you rebuild and install with master to verify this issue?
