### ISSUE TITLE
Ubuntu 18.04 Install - Missing Python Dependencies

### ISSUE THREAD

**Issue by pepck-svc** [regel/loudml#113]
Installing loudml on Ubuntu 18.04 using the apt repository resulted in the following errors when starting the loumld service:

`Apr 29 08:34:38 loudml loudmld[522]: Traceback (most recent call last):
Apr 29 08:34:38 loudml loudmld[522]:   File "/usr/bin/loudmld", line 6, in <module>
Apr 29 08:34:38 loudml loudmld[522]:     from pkg_resources import load_entry_point
Apr 29 08:34:38 loudml loudmld[522]: ModuleNotFoundError: No module named 'pkg_resources'
Apr 29 08:34:38 loudml systemd[1]: loudmld.service: Main process exited, code=exited, status=1/FAILURE
`
Quick search showed the missing package is python-setuptools.

Tried installing python3-setuptools from the Ubuntu repo, but this did not resolve the problem.

**Installing setuptools via pip resolved the issue**, allowing the service to start. Note that the system used did not have pip installed already, so a large number of packages was installed- unclear exactly which ones were needed.

**Comment by regel** [comment]
Hi @pepck-svc thanks for the info. You can submit a pull request to help enhance the documentation for others. 

Guide: `https://loudml.io/guide/en/loudml/reference/current/ubuntu.html`

Doc file in this repo: `docs/reference/setup/install/ubuntu.asciidoc`

**Comment by regel** [comment]
Updated setup guide: https://loudml.io/en/loudml/reference/current/setup.html
