### ISSUE TITLE
Influxdb datasource not found

### ISSUE THREAD

**Issue by ramchinthamsetty** [regel/loudml#115]
I configured loudml.yml as below:

datasources:
  - name: capacity_model
    type: influxdb
    addr: localhost:8086
    database: capacity_management
    retention_policy: autogen
storage:
  path: /kafka/loudml/var/lib/loudml

server:
  listen: 0.0.0.0:8077

I have created a model as below, which is successful:

{
        "name":"capacity_model",
        "offset": 30,
        "features":[

                {
                    "metric": "avg",
                    "field": "disk_percent_use",
                    "name": "mean_exchange_disk_usage",
                    "default": 0,
                    "measurement": "capacity_disk_metrics",
                    "anomaly_type": "low_high"
                }

        ],
        "bucket_interval": "1d",
        "min_threshold": 75,
        "max_threshold": 95,
        "default_datasource": "capacity_management",
        "retention_policy":"autogen",
        "interval": "1d",
        "max_evals": 5,
        "type": "donut",
        "span": 10,
        "forecast": 5,
        "seasonality": {
            "daytime": true,
            "weekday": true
        }
}

But, now i wanted to train the mode, which doesnt work as it reports the following error:

ERROR:root:Data source not found (name = 'capacity_management')

But, I do have database name called 'capacity_management' in InfluxDB.

Would you please help?

**Comment by regel** [comment]
@ramchinthamsetty 

Hi, your JSON model file uses `"default_datasource": "capacity_management"` but your config.yml file declared a `capacity_model` source.

For clarity you can rename both to `capacity_datasource`, eg your `config.yml` file can be:

```
datasources:
  - name: capacity_datasource
    type: influxdb
    addr: localhost:8086
    database: capacity_management
    retention_policy: autogen
```

and your JSON model file can be:

```
{
    "name":"capacity_model",
    "offset": 30,
    "features":[

            {
                "metric": "avg",
                "field": "disk_percent_use",
                "name": "mean_exchange_disk_usage",
                "default": 0,
                "measurement": "capacity_disk_metrics",
                "anomaly_type": "low_high"
            }
    ],
    "bucket_interval": "1d",
    "min_threshold": 75,
    "max_threshold": 95,
    "default_datasource": "capacity_datasource",
    "interval": "1d",
    "max_evals": 5,
    "type": "donut",
    "span": 10
}
```

**Comment by regel** [comment]
@ramchinthamsetty I noticed that it's been a little while since we last heard from you, and I wanted to check in to remind you about this ticket.

Can we close this ticket? You can always respond to the ticket to reopen it if needed.
