### ISSUE TITLE
Cannot save prediction if parameter if "match_all" is defined for elastic datasource

### ISSUE THREAD

**Issue by nonostar** [regel/loudml#117]
If I define a match section in my model, for example:
`"match_all": [ {"tag": "event.dataset.keyword", "value": "system.cpu"} ]`

Creation and training run both fine but writing prediction fails in elastic datasource:
`curl -X POST "http://localhost:8077/models/model_test/_start?save_prediction=true`

will result:
`elasticsearch.helpers.BulkIndexError:` ('1 document(s) failed to index [...]
'error': {'type': 'mapper_parsing_exception', 'reason': 'Could not dynamically add mapping for field [event.dataset.keyword]. Existing mapping for [event.dataset] must be of type object but found [text].'}`

loudmld is trying to write to a json object as text...

**Comment by nonostar** [comment]
Ok It works, I added this dirty fix in the file elastic.py, for the function send_bulk:
     `for i in range(len(requests)):
                for key in requests[i]['_source']:
                        if 'keyword' == key.split('.')[-1]:
                                newkey = key.replace('.keyword','')
                                requests[i]['_source'][newkey] = requests[i]['_source'].pop(key)
`
I don't know ( and i don't really wanna know ) how is created the list 'requests' amongs all these functions and files, so I edited just before it's sent to elastic datasource.

**Comment by nonostar** [comment]
Writing prediction is still quite buggy.
You should use, at least, the type "date" for the specified model's parameter "timestamp_field". My timestamp field finaly had the type "long" and I had to change it with index template.
Using inline "painless script" functionnality just for matching tag instead of a classic elastic term query is really weird but I imagine you had some constraints I don"t know to do this nonsens.

**Comment by nonostar** [comment]
You should plan to add the possibility to write prediction to another datasource than the one used to learn.
For compliance, performance or big mess issues ;)

**Comment by nonostar** [comment]
I changed again function send_bulk, ugly but it suits my need

```python
    def send_bulk(self, requests):
        """
        Send data to Elasticsearch
        """
        def dot_to_json(a):
            from functools import reduce
            output = {}
            for key, value in a.items():
                path = key.split('.')
                target = reduce(lambda d, k: d.setdefault(k, {}), path[:-1], output)
                target[path[-1]] = value
            return output
        logging.info("commit %d change(s) to elasticsearch", len(requests))
        for i in range(len(requests)):
                for key in requests[i]['_source']:
                        if 'keyword' == key.split('.')[-1]:
                                newkey = key.replace('.keyword','')
                                requests[i]['_source'][newkey] = requests[i]['_source'].pop(key)
                        key_split = key.split('.')
                requests[i]['_source'] = dot_to_json(requests[i]['_source'])
        try:
            helpers.bulk(
                self.es,
                requests,
                chunk_size=5000,
                timeout="30s",
            )
        except (
            urllib3.exceptions.HTTPError,
            elasticsearch.exceptions.TransportError,
        ) as exn:
            raise errors.TransportError(str(exn))
```

**Comment by nonostar** [comment]
I exchanged left/right side of "upper_" / "lower_" of predicted metric's name in donut.py because it was not convenient to sort it among lot of others.

**Comment by regel** [comment]
@nonostar Hi, thank you for your contribution! Let me have a look.

>You should plan to add the possibility to write prediction to another datasource than the one used to learn.

Our docs really need an update. You can do it. Your model description can define a "source" and a "sink". Your JSON settings can include the following parameters. If you want all predictions in the same index     you can set `"default_datasink": "loudml"` and they will be saved and tagged according to the model name.

```
    "default_datasource": "your_input_source",
    "default_datasink": "your_output_source",
```

Sinks and sources use the same syntax in your config.yml and sit under the datasources list.

Our main struggle with ES is to maintain compatibility with all versions. The official py library claims compatibility with only one major release. The root cause of the .keyword issue (and similar with long timestamp rather than dates) is the change in how to PUT an index template.

```
For Elasticsearch 7.0 and later, use the major version 7 (7.x.y) of the library.

For Elasticsearch 6.0 and later, use the major version 6 (6.x.y) of the library.

For Elasticsearch 5.0 and later, use the major version 5 (5.x.y) of the library.

For Elasticsearch 2.0 and later, use the major version 2 (2.x.y) of the library, and so on.
```

**Comment by regel** [comment]
@nonostar this is solved on master.
