### ISSUE TITLE
New Install Ubuntu 18.04 Docs Incorrect

### ISSUE THREAD

**Issue by PenteonDevTeam** [regel/loudml#136]
**New Install on AWS on Ubuntu 18.04**
Using Instructions at:  https://loudml.io/en/loudml/reference/current/ubuntu.html
and    https://loudml.io/en/loudml/reference/current/_setup_your_config_yml_file.html

Following these instructions I performed the following with unsuccessful results:

**Download and install the public signing key:**
wget -qO - http://loudml.s3-website-eu-west-1.amazonaws.com/repo/gpg/GPG-KEY-LOUDML | sudo apt-key add -

**Installed Dependencies:**
apt-get install python3-lib2to3

**Installed APT Repositories:**
sudo apt-get install apt-transport-https
echo "deb http://loudml.s3-website-eu-west-1.amazonaws.com/repo/1.x/ubuntu/18.04/amd64 bionic main" | sudo tee -a /etc/apt/sources.list.d/loudml-1.x.list

**Installed LoudML (I see that you still list the loudml-elastic and loudml-influx here but apparently not needed any more - see also missing files in the manual install section for these two items as they are listed in your docs but no longer on the server):**
sudo apt-get update && sudo apt-get install loudml

**Edited the LoudML config.yml:**
datasources: []
 -  name: influx
   type: influxdb
   addr: [myserveraddress]:8086
   database: sensordata

storage:
   path: /var/lib/loudml

server:
  listen: 0.0.0.0:8077

Started LoudML:
sudo systemctl start loudmld.service

ERROR:  
Aug 27 19:50:23 ip-10-0-0-178 systemd[1]: Stopped Loud ML daemon.
Aug 27 19:50:23 ip-10-0-0-178 systemd[1]: Started Loud ML daemon.
Aug 27 19:50:24 ip-10-0-0-178 loudmld[5585]: ERROR:root:while parsing a block mapping
Aug 27 19:50:24 ip-10-0-0-178 loudmld[5585]:   in "/etc/loudml/config.yml", line 1, column 1
Aug 27 19:50:24 ip-10-0-0-178 loudmld[5585]: expected <block end>, but found '<block sequence start>'
Aug 27 19:50:24 ip-10-0-0-178 loudmld[5585]:   in "/etc/loudml/config.yml", line 2, column 2
Aug 27 19:50:24 ip-10-0-0-178 systemd[1]: loudmld.service: Main process exited, code=exited, status=1/FAILURE

_____

Any suggestions as to what is missing or misconfigured??

Thank you,

Clay S Perreault

**Comment by pahowart** [comment]
Your YAML syntax isn't valid. Use something like yamllint.com to verify your config. 

Using something like the following should clear the error.

--- 
datasources: 
  - 
    addr: "10.0.0.0:8086"
    database: sensordata
    name: influx
    type: influxdb

**Comment by regel** [comment]
Updated installation guide: https://loudml.io/en/loudml/reference/current/install-loudml.html
