### ISSUE TITLE
CentOS 7.6 Install. loudmld.service failing to start.

### ISSUE THREAD

**Issue by empumd** [regel/loudml#137]
CentOS 7.6 Installation via repository following instructions on: 

_https://loudml.io/en/loudml/reference/current/rpm.html_

Python Version is 3.6.8
I also updated pip and setuptools.

Starting loudmld.service I get the following Errors:
```

Traceback (most recent call last):
  File "/usr/bin/loudmld", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'loudml==1.5.0' distribution was not found and is required by the application
```

Could this be a permission issue? Maybe anything I have to change in the docs?

Regards,
Max

**Comment by osunac** [comment]
Hi.

Thanks for the bug report.

## Observed behavior
The programs `loudml` and `loudmld` cannot start. The following message is printed on screen.
```
pkg_resources.DistributionNotFound: The 'loudml==1.5.0' distribution was not found and is required by the application
```

## Root Cause Analysis
At the time the packages were built, Python 3.4 was the default Python 3 interpreter for CentOS 7. Since then, Python 3.6 has become the default interpreter. As a result, the programs are now started with an interpreter that cannot load the Loud ML packages.

## Bugfix
Rebuild the packages for Python 3.6. Make sure the packages depend on that version.

## Workaround
Force the interpreter to be Python 3.4.
```
$ sudo yum install -y python34 python34-setuptools
$ sudo sed -i "s/python3/python3.4/" /usr/bin/loudml
$ sudo sed -i "s/python3/python3.4/" /usr/bin/loudmld
```

**Comment by regel** [comment]
There is no RPM yet for the latest 1.6 release, but you can clone the source code locally and run: `make rpm` at the root of the directory to generate them.

See also the file `base/README.rst` for instructions before you run the make rpm command.

One hack is to get the RPM files from CircleCI using the daily night build:

- Open https://circleci.com/gh/regel/workflows/loudml/tree/master
- Search for 'nightly@master' workflow
- Click on 'build-rpm' if it's in green status
- Click on the 'Artifacts' tab. You should see two files under the 'x86_64' label

**Comment by regel** [comment]
Solved.

Fedora COPR pipeline builds rpm continuously. The repository can be enabled via:

`$ dnf copr enable regel/loudml
`
