### ISSUE TITLE
Training fails with "failed: Abnormal termination"

### ISSUE THREAD

**Issue by AddChickpeas** [regel/loudml#138]
Hello, 

I'm trying to set up my model and am running into the follow error: 

> [2019-09-03 23:30:26] "POST /models/deny-model/_train?from=now-1h HTTP/1.1" 200 147 0.002047       │
│ ERROR:root:job[a4e3ff70-975f-4ad3-9b6f-c0e6a772ff53] failed: Abnormal termination

Note: the time frame is so short because this is a new index and I'm just testing that I can get it to work at all at the moment. 

Here is the json I used to create the model: 
> {
  "timestamp_field": "@timestamp",
  "bucket_interval": "1m",
  "default_datasource": "elasticsearch",
  "features": [
    {
      "default": 0,
      "field": "Deny_count",
      "metric": "sum",
      "name": "deny-count"
    }
  ],
  "interval": 60,
  "max_evals": 10,
  "name": "deny-model",
  "offset": 30,
  "span": 5,
  "max_threshold": 0,
  "min_threshold": 0,
  "type": "donut"
}

I made this index just for testing. I had initially wanted to do a count of deny's directly from our firewall index, but received an error indicating it had to be a numeric field. 

To work around this, I used Fluentd to output a new index with the doc counts of different fields at 10s intervals. 

At this point, I've sorted out the various network policy and permissions issues and am able to communicate with Elasticsearch successfully. Unsure what to make of this error as it isn't all that descriptive.

Not sure if it would make a difference, but we are running this in a Kubernetes pod in the same cluster as our Elasticsearch instance.

**Comment by regel** [comment]
cc: @robcowart for Elasticsearch setup. What is your Elasticsearch version?

You can totally run it with Kubernetes and pods. You can get more logs on the server using `journalctl -xfeu loudmld`

Very nice to see you are using the POST queries. fyi we are now creating API clients in Python, Go, and Javascript for easier integration. Url for these new OSS projects: 

- https://github.com/loudml/loudml-python
- https://github.com/loudml/loudml-go
- https://github.com/loudml/loudml-js

The first release for Python and Go client libs will be available in the coming days and we will probably cut a 1.6.0 release in a short while.

Contributions and ideas are welcome! We need help for Javascript contributions!

**Comment by regel** [comment]
When you see this log you can do `curl -X GET pod:8077/jobs/a4e3ff70-975f-4ad3-9b6f-c0e6a772ff53` to get more error information.

>ERROR:root:job[a4e3ff70-975f-4ad3-9b6f-c0e6a772ff53] failed: Abnormal termination

Given the short time range it's possible that there is not enough data to train the model.

**Comment by AddChickpeas** [comment]
Resolved this issue. Likely due to small dataset as mentioned. Now hitting other errors while I'll document in a new issue.
