### ISSUE TITLE
Train and predict: ERROR:root:%s (type = '%s') (version 1.2.2)

### ISSUE THREAD

**Issue by syntrop** [regel/loudml#14]
Hi
I managed to create model, but not able to run `train` or `predict`

It shows me (executed as root):

```
loudml train --from "now-4d" --to "now" log_model
ERROR:root:%s (type = '%s')
```

or with another model train/predict
```
loudml train --from "now-4d" --to "now" avg_temp2-model
ERROR:root:%s (type = '%s')

loudml predict --from "now-1d" --to "now" avg_temp2-model -b

ERROR:root:%s (type = '%s')

```

and if I execute this as normal user:
```
loudml predict --from "now-1d" --to "now" avg_temp2-model -b
/usr/lib/python3/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
ERROR:root:%s (type = '%s')
```

**Comment by vnyb** [comment]
Error formatting will be fixed in 1.2.3.
It seems that the package for the datasource you use is not installed.

For InfluxDB, install `loudml-influx`:

```
yum install loudml-influx
```
or
```
apt-get install loudml-influx
```

For Elasticsearch, install `loudml-elastic`:

```
yum install loudml-elasticsearch
```
or
```
apt-get install loudml-elasticsearch
```

**Comment by syntrop** [comment]
In my case I can not use standard apt-get because of this:
E: Failed to fetch http://loudml.s3-website-eu-west-1.amazonaws.com/repo/deb/packages/1.x/apt/dists/stable/main/binary-amd64/Packages  404  Not Found

Then I've tried to install manually http://loudml.io/guide/en/loudml/reference/current/deb.html#install-deb

But there is no info in the doc about how can I get loudml-influx or other packages manually.

Could you point me to the right source?

**Comment by osunac** [comment]
Documentation has been updated.

Could you try to run again the instructions from the documentation?

- repository definition (URL has been updated)
- ``apt-get update``
- ``apt-get install -y loudml loudml-influx``

**Comment by regel** [comment]
fixed the documentation
