### ISSUE TITLE
loudml stopped with loudml-api not found error

### ISSUE THREAD

**Issue by HazelCindy** [regel/loudml#142]
my logs are
 Traceback (most recent call last):
Ful 10 13:49:27  loudmld[25175]:   File "/usr/bin/loudmld", line 11, in <module>
Ful 10 13:49:27  loudmld[25175]:     load_entry_point('loudml==1.5.0', 'console_scripts', 'loudmld')()
Ful 10 13:49:27  loudmld[25175]:   File "/usr/lib/python3/dist-packages/loudml/server.py", line 1085, in main
Ful 10 13:49:27  loudmld[25175]:     loudml.config.load_plugins(args.config)
Ful 10 13:49:27  loudmld[25175]:   File "/usr/lib/python3/dist-packages/loudml/config.py", line 142, in load_plugins
Ful 10 13:49:27  loudmld[25175]:     ep.load()(ep.name, path)
Ful 10 13:49:27  loudmld[25175]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2323, in load
Ful 10 13:49:27 loudmld[25175]:     self.require(*args, **kwargs)
Ful 10 13:49:27 loudmld[25175]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2346, in require
Ful 10 13:49:27  loudmld[25175]:     items = working_set.resolve(reqs, env, installer, extras=self.extras)
Ful 10 13:49:27 loudmld[25175]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
Ful 10 13:49:27  loudmld[25175]:     raise DistributionNotFound(req, requirers)
Ful 10 13:49:27  loudmld[25175]: pkg_resources.DistributionNotFound: The 'loudml-api' distribution was not found and is required by the application
Ful 10 13:49:27  systemd[1]: loudmld.service: Main process exited, code=exited, status=1/FAILURE

**Comment by regel** [comment]
Hi, if pkg_resources complains you may need to clean up any previously installed version.

`loudml-api` no longer exists. Everything is bundled now into `loudml` (the core package) and `loudml-base` (all .py dependencies) to reduce the number of packages involved.

What is your OS? What is the package file you are using? Are you running/not running in a virtual env?

Apologies for 1.5 documentation that we need to fix. You can refer instead to the `master` version and this one should be up to date.

**Comment by HazelCindy** [comment]
I am using loudml 1.5 Debian package and it's the only version I have. I am not running it in a virtual environment. My os is Ubuntu 18.04Sent from my Huawei phone-------- Original Message --------Subject: Re: [regel/loudml] loudml stopped with loudml-api not found error (#142)From: Sebastien Leger To: regel/loudml CC: HazelCindy ,Author Hi, if pkg_resources complains you may need to clean up any previously installed version.
loudml-api no longer exists. Everything is bundled now into loudml (the core package) and loudml-base (all .py dependencies) to reduce the number of packages involved.
What is your OS? What is the package file you are using? Are you running/not running in a virtual env?
Apologies for 1.5 documentation that we need to fix. You can refer instead to the master version and this one should be up to date.
