### ISSUE TITLE
Links Broken!

### ISSUE THREAD

**Issue by masongk** [regel/loudml#143]
Pre-built packages link, Documentation link,  getting started guide links are broken

**Comment by regel** [comment]
Hi,

Thank you for reporting this. What links are broken exactly?

Documentation is deployed by Netlify and seems to work at https://loudml.io

Docker images are on docker hub. The latest Docker images include CPU or GPU support; fyi there is no GPU support in the RPM - DEB files. Docker tag '*-latest' are automatically rebuilt every night after checkout of the master revision.

A small hack: for .rpm or .deb pre-built packages, can you try to access CircleCI artifacts where we build the master branch continuously?

Steps:

- https://circleci.com/gh/regel/loudml/tree/master
- Click on `build-rpm` or `build-deb` jobs, and then click on the Artifacts tab to download the files

Or (worst-case) repeating the build by checking out the master and running the relevant make tasks.

**Comment by regel** [comment]
The /guide redirect was giving a 404 and is fixed now.

Anything else?

**Comment by masongk** [comment]
That's all for now. Thanks!
