### ISSUE TITLE
'search_phase_execution_exception', 'failed to parse date field' | GRAYLOG + Elastic backend

### ISSUE THREAD

**Issue by piellick** [regel/loudml#149]
Hi everyone, 
when graylog is using in front of Elasticsearch for log management, a specific time format is used and training crash.

**loudML version :** latest docker image
{"host_id":"3d919776204fddded5e557fa72242330","tagline":"The Disruptive Machine Learning API","version":"1.6.0-446132b4"}

**Elasticsearch version :** 6.7.1
**Graylog version :** 3.0.1

Here is the log output : 
```

INFO:root:job[a198e0ec-0925-4696-9b92-bb0fa0eccc5e] starting, nice=5
--
  | INFO:root:train(count-model2) range=2019-10-02T13:50:00.000Z-2019-10-02T13:51:00.000Z train_size=0.670000 batch_size=64 epochs=100)
  | INFO:root:connecting to elasticsearch on es-cluster-0:9200
  | 10.131.4.1 - - [2019-10-02 13:50:50] "POST /models/count-model2/_train?from=now-5s&to=now HTTP/1.1" 202 153 0.218694
  | ERROR:concurrent.futures:exception calling callback for <ProcessFuture at 0x7f584dd47898 state=finished raised TransportError>
  | pebble.common.RemoteTraceback: Traceback (most recent call last):
  | File "/usr/lib/python3/dist-packages/loudml/elastic.py", line 430, in search
  | params=params,
  | File "/usr/lib/loudml/vendor/elasticsearch/client/utils.py", line 76, in _wrapped
  | return func(*args, params=params, **kwargs)
  | File "/usr/lib/loudml/vendor/elasticsearch/client/__init__.py", line 660, in search
  | doc_type, '_search'), params=params, body=body)
  | File "/usr/lib/loudml/vendor/elasticsearch/transport.py", line 318, in perform_request
  | status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  | File "/usr/lib/loudml/vendor/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
  | self._raise_error(response.status, raw_data)
  | File "/usr/lib/loudml/vendor/elasticsearch/connection/base.py", line 125, in _raise_error
  | raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
  | **elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'failed to parse date field [1570024200000] with format [yyyy-MM-dd HH:mm:ss.SSS]')**
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/usr/lib/loudml/vendor/pebble/common.py", line 174, in process_execute
  | return function(*args, **kwargs)
  | File "/usr/lib/python3/dist-packages/loudml/worker.py", line 351, in run
  | return g_worker.run(job_id, nice, func_name, *args, **kwargs)
  | File "/usr/lib/python3/dist-packages/loudml/worker.py", line 55, in run
  | raise exn
  | File "/usr/lib/python3/dist-packages/loudml/worker.py", line 53, in run
  | res = getattr(self, func_name)(*args, **kwargs)
  | File "/usr/lib/python3/dist-packages/loudml/worker.py", line 101, in train
  | **kwargs
  | File "/usr/lib/python3/dist-packages/loudml/donut.py", line 1051, in train
  | for i, (_, val, timeval) in enumerate(data):
  | File "/usr/lib/python3/dist-packages/loudml/elastic.py", line 567, in get_times_data
  | routing=None,
  | File "/usr/lib/python3/dist-packages/loudml/elastic.py", line 433, in search
  | raise errors.TransportError(str(exn))
  | loudml.errors.TransportError: <unprintable TransportError object>

```
Mapping schema on elasticsearch for Graylog's managed indices:
![image](https://user-images.githubusercontent.com/18485789/66051870-e766ac00-e52f-11e9-8d58-429efba01a3d.png)

**Comment by regel** [comment]
We need a few things:
 * the model information. Run show-model to dump the settings
 * the logs produced in elasticsearch.log they usually contain more details about the exception

Your training range is 5 seconds `from=now-5s&to=now`. You can increase this range.

Also include the following settings in `/etc/elasticsearch/elasticsearch.yml` to avoid time series limitations in Elasticsearch.

```
indices.query.bool.max_clause_count: 8192
search.max_buckets: 100000
```

**Comment by wooyey** [comment]
Well I've faced with similar issue on new Elasticsearch (7.6.2). 
I've made some patches - quite easy for 7.x and more generic (which I don't like too much ;))
If you are interested in I can send you patches for review (according to your contribution guide) by the end of this week.
You know, need to cleanup it first...

**Comment by regel** [comment]
Hi Woo! This will be awesome! Please open a pull-request so I can help to clean it up

I'm also interested in your opinion on: https://github.com/regel/loudml/pull/279

Updating this dependency seems OK at first. It passes unit tests. Still, we could find a blind spot in this update.

**Comment by wooyey** [comment]
Hey Sebastien!

Sorry for late response... I'm just too lazy bastard ...
After going through ES documentation from 2.x till 7.x it seems that it's quite trivial patch to specify explicit time format. So it's one liner now. 
Unfortunately I cannot run default queries using "painless" code which:
- I don't know why is there ...
- Produce deprecated warnings on my ES version (7.6.2)
- Doesn't like my indices definition ES and ends up with an error:

> Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. 

`match` is just simpler ... and works out of the box :)

About #279 ... sorry I cannot help you with that too much - in my case it wasn't ES client library problem but query. Still I believe that this uplift shouldn't break ... too much ...

**Comment by regel** [comment]
Merged https://github.com/regel/loudml/pull/305
