### ISSUE TITLE
Debian/Ubuntu packages unavailable

### ISSUE THREAD

**Issue by KevinM23** [regel/loudml#166]
Hi,

Following this instructions:
https://loudml.io/en/loudml/reference/1.5/install-loudml.html

The commands:
```
wget http://loudml.s3-website-eu-west-1.amazonaws.com/repo/deb/pool/main/l/loudml-influx/loudml-influx_1.5.0_all.deb
wget http://loudml.s3-website-eu-west-1.amazonaws.com/repo/deb/pool/main/l/loudml-elastic/loudml-elastic_1.5.0_all.deb
```

And:
```
wget http://loudml.s3-website-eu-west-1.amazonaws.com/repo/1.x/ubuntu/18.04/amd64/pool/main/l/loudml-influx/loudml-influx_1.5.0_all.deb
wget http://loudml.s3-website-eu-west-1.amazonaws.com/repo/1.x/ubuntu/18.04/amd64/pool/main/l/loudml-elastic/loudml-elastic_1.5.0_all.deb
```

Return 'ERROR 404 not found' errors.

**Comment by regel** [comment]
So the plan here with 1.6 is to publish DEB files using OBS build service, and RPMs using COPR build service for Fedora distributions. We have to use all standard services available to Open source projects and then update documentation.

Meanwhile, the latest versions are still published on Docker Hub.

**Comment by regel** [comment]
WIP. New deb files will be available and built continuously in the CICD pipeline in the next 5-6 days.

**Comment by regel** [comment]
All debian/* files needed to build Debian packages are now available in `develop` branch. I have tested packaging with Debian stretch, buster, Ubuntu xenial and Ubuntu bionic. So far, so good.

However, finding affordable Debian package hosting is yet another issue. I'm setting up a dedicated APT repository and file hosting on S3. Work in progress.

**Comment by regel** [comment]
I did it! Setting up this Debian/Ubuntu repo was SO hard but I believe it's done the right way. HTTPS and GPG signatures enabled.

```
$ curl -s https://deb.loudml.io/install/script.deb.sh | sudo bash
Detected operating system as Ubuntu/bionic.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/loudml.list...done.
Importing gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
```

So now you can do `apt-get install loudml` on a modern Debian and Ubuntu and it will work.

One exception: I could not do Ubuntu Xenial (16.04), python 3.5 is no longer supported in so many pip packages that I have to drop support for Xenial.

If you like this work, please give a star to the repo!

**Comment by regel** [comment]
Solved. Please refer to the setup guide: https://loudml.io/en/loudml/reference/current/install-loudml.html
