### ISSUE TITLE
LoudML out of nowhere removes all retention policies and respective data

### ISSUE THREAD

**Issue by Xavear** [regel/loudml#167]
Dear all,

I'm currently running loudml 1.5.0 and train my models via loudml/chronograf 1.6.1. Three models where trained successfully and had been running for several days. But out of the blue all my retention policies got deleted, making me lose all the respective data. This has already happend twice now.

Does anybody have a clue what might cause this or what might fix it?

Thanks a lot!

Thom

**Comment by regel** [comment]
Hi Thom, the code in influxdb.py reads and writes (new) data points. So I have no clue on what happens in the problem described.

Try to enable influxdb debug logs including log queries to clear any doubts about incoming queries.

**Comment by regel** [comment]
Set for troubleshooting 'query-log-enabled = true' and then restart the service. This will log all queries and make it easier to spot DELETE queries or inspect the logs if the issue is reproduced.

setting in `influxdb.conf`:

influxdb.conf
[data]
...
query-log-enabled = true
