### ISSUE TITLE
can not create prediction dashboard for model

### ISSUE THREAD

**Issue by trungkysis** [regel/loudml#168]
influxdb : latest
telegraf : latest
loudml/chronograf : 1.6.1
loudml/community : 1.5.0

After trained model, could not link to dashboard or start forecasting.

<img width="1440" alt="Screen Shot 2019-12-17 at 16 56 02" src="https://user-images.githubusercontent.com/38279466/70985406-a4f44a80-20ee-11ea-9e36-d810691788d9.png">

**Comment by regel** [comment]
I am facing the same issue. The ‘create dashboard’ menu no longer works and I need to investigate why.

**Comment by regel** [comment]
ETA: this Wednesday

**Comment by regel** [comment]
Solved btw. Seems like I forgot to update Github.
The new docker compose file is available on master. The core functions are here, minus one or two issues that I will resolve later.

**Comment by trungkysis** [comment]
thanks so much
