### ISSUE TITLE
Source code of the .deb package is missing

### ISSUE THREAD

**Issue by RomanPlusPlus** [regel/loudml#204]
Hi! I would like to build the entirety of Loud ML from source files. 
But I'm unable to find the source code for the .deb package that is required according to the [Install Loud ML page](https://loudml.io/en/loudml/reference/1.5/install-loudml.html).
Where can I find it?
Thank you!

**Comment by regel** [comment]
Hi.

You can. The source code is in Python and uses standard packaging practices.

Wait a few days, I'm working on the DEB packages release using the OBS service. Meanwhile, I'd recommend using Docker images already available on Docker hub: https://hub.docker.com/r/loudml/loudml

**Comment by regel** [comment]
WIP. New deb files will be available and built continuously in the CICD pipeline in the next 5-6 days.

**Comment by regel** [comment]
All debian/* files needed to build Debian packages are now available in `develop` branch. I have tested packaging with Debian stretch, buster, Ubuntu xenial and Ubuntu bionic. So far, so good.

However, finding affordable Debian package hosting is yet another issue. I'm setting up a dedicated APT repository and file hosting on S3. Work in progress.

**Comment by regel** [comment]
I did it! Setting up this Debian/Ubuntu repo was SO hard but I believe it's done the right way. HTTPS and GPG signatures enabled.

```
$ curl -s https://deb.loudml.io/install/script.deb.sh | sudo bash
Detected operating system as Ubuntu/bionic.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/loudml.list...done.
Importing gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
```

So now you can do `apt-get install loudml` on a modern Debian and Ubuntu and it will work.

One exception: I could not do Ubuntu Xenial (16.04), python 3.5 is no longer supported in so many pip packages that I have to drop support for Xenial.

If you like this work, please give a star to the repo!

**Comment by RomanPlusPlus** [comment]
Hi Regel, thank you for your hard work! I'll try to build it from source files and will report the results.
