### ISSUE TITLE
training failed

### ISSUE THREAD

**Issue by langerma** [regel/loudml#220]
Good Evening,

I tried to train a model on opentsdb but somehow it ends up with an error:
`127.0.0.1 - - [2020-02-26 17:36:35] "POST /models/opentsdb-test/_train?epochs=100&max_evals=10&from=now-90d&to=now&continue=False HTTP/1.1" 202 153 0.041613
I0226 17:36:35.877790 548386684944 worker.py:45] job[8b36f0c9-7093-4251-81f6-09e75beba377] starting, nice=5
I0226 17:36:35.946151 548386684944 donut.py:1028] train(opentsdb-test) range=2019-11-28T16:36:00.000Z-2020-02-26T16:37:00.000Z train_size=0.670000 batch_size=64 epochs=100)
I0226 17:36:35.946992 548386684944 opentsdb.py:269] connecting to opentsdb on x.x.x.x:4242
127.0.0.1 - - [2020-02-26 17:36:36] "GET /jobs/8b36f0c9-7093-4251-81f6-09e75beba377?fields=result&include_fields=false HTTP/1.1" 200 313 0.006920
127.0.0.1 - - [2020-02-26 17:36:37] "GET /jobs/8b36f0c9-7093-4251-81f6-09e75beba377?fields=result&include_fields=false HTTP/1.1" 200 313 0.007675
127.0.0.1 - - [2020-02-26 17:36:38] "GET /jobs/8b36f0c9-7093-4251-81f6-09e75beba377?fields=result&include_fields=false HTTP/1.1" 200 313 0.009050
127.0.0.1 - - [2020-02-26 17:36:39] "GET /jobs/8b36f0c9-7093-4251-81f6-09e75beba377?fields=result&include_fields=false HTTP/1.1" 200 313 0.003500
127.0.0.1 - - [2020-02-26 17:36:40] "GET /jobs/8b36f0c9-7093-4251-81f6-09e75beba377?fields=result&include_fields=false HTTP/1.1" 200 313 0.005847
127.0.0.1 - - [2020-02-26 17:36:41] "GET /jobs/8b36f0c9-7093-4251-81f6-09e75beba377?fields=result&include_fields=false HTTP/1.1" 200 313 0.002524
127.0.0.1 - - [2020-02-26 17:36:42] "GET /jobs/8b36f0c9-7093-4251-81f6-09e75beba377?fields=result&include_fields=false HTTP/1.1" 200 313 0.002218
127.0.0.1 - - [2020-02-26 17:36:43] "GET /jobs/8b36f0c9-7093-4251-81f6-09e75beba377?fields=result&include_fields=false HTTP/1.1" 200 312 0.002239
127.0.0.1 - - [2020-02-26 17:36:45] "GET /jobs/8b36f0c9-7093-4251-81f6-09e75beba377?fields=result&include_fields=false HTTP/1.1" 200 313 0.002196
I0226 17:36:45.679394 548386684944 donut.py:1064] found 129602 time periods
E0226 17:36:45.691788 548386684944 worker.py:57] 'generator' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/loudml-1.6.0-py3.6.egg/loudml/worker.py", line 53, in run
    res = getattr(self, func_name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/loudml-1.6.0-py3.6.egg/loudml/worker.py", line 101, in train
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/loudml-1.6.0-py3.6.egg/loudml/donut.py", line 1091, in train
    abnormal=abnormal,
  File "/usr/local/lib/python3.6/dist-packages/loudml-1.6.0-py3.6.egg/loudml/donut.py", line 843, in _train_on_dataset
    rstate=fmin_state,
  File "/usr/local/lib/python3.6/dist-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/usr/local/lib/python3.6/dist-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/usr/local/lib/python3.6/dist-packages/hyperopt/fmin.py", line 314, in fmin
    pass_expr_memo_ctrl=pass_expr_memo_ctrl)
  File "/usr/local/lib/python3.6/dist-packages/hyperopt/base.py", line 786, in __init__
    pyll.toposort(self.expr)
  File "/usr/local/lib/python3.6/dist-packages/hyperopt/pyll/base.py", line 715, in toposort
    assert order[-1] == expr
TypeError: 'generator' object is not subscriptable
E0226 17:36:45.697966 548348031472 server.py:389] job[8b36f0c9-7093-4251-81f6-09e75beba377] failed: 'generator' object is not subscriptable`

the model i used:
`{
        "bucket_interval": "60s",
        "default_bucket": "opentsdb",
        "features":
        [
                {
                        "name": "avg_load1",
                        "measurement": "system_load1",
                        "field": "system_load1",
                        "metric": "avg",
                        "default": null,
                        "anomaly_type": "low_high"
                }
        ],
        "interval": "60s",
        "max_evals": 10,
        "offset": "10s",
        "span": 10,
        "type": "donut",
        "name": "opentsdb-test"
}`

**Comment by langerma** [comment]
any update on this?

**Comment by vsergeyev** [comment]
Hello @langerma 

I'm going to check if OpenTSDBBucket working well.
Will use your model with some random data here.

Regards,
V.

**Comment by langerma** [comment]
okay thx. if you need any additional information, i'd be glad to share

**Comment by vsergeyev** [comment]
@langerma during investigating your issue, I have found an error in query results alignment.
https://github.com/regel/loudml/pull/253

But this is a case after model has been trained. This is a step where it runs.

I used similar model you have with only one major difference - train data was for ~3 hours.
May you please try a smaller dataset on your side after this pull request will be merged.

Regards,
V.

**Comment by langerma** [comment]
i will try.

**Comment by regel** [comment]
Pull-request from Volodymyr merged in `develop`

**Comment by langerma** [comment]
seems like the error is still there:

`> train-model -f now-1h opentsdb-test
training(opentsdb-test): : 1it [00:01,  1.02s/it]
'generator' object is not subscriptable`

and loudml log:
`127.0.0.1 - - [2020-04-07 23:27:26] "POST /models/opentsdb-test/_train?epochs=100&max_evals=10&from=now-1h&to=now&continue=False HTTP/1.1" 202 153 0.011060
I0407 23:27:26.895211 548067610640 worker.py:45] job[f9c52c44-5397-4bb9-914c-1a096e5406e6] starting, nice=5
I0407 23:27:26.901166 548067610640 donut.py:1028] train(opentsdb-test) range=2020-04-07T20:27:20.000Z-2020-04-07T21:27:30.000Z train_size=0.670000 batch_size=256 epochs=100)
I0407 23:27:26.901780 548067610640 opentsdb.py:276] connecting to opentsdb on x.x.x.x:4242
I0407 23:27:26.991566 548067610640 donut.py:1064] found 361 time periods
E0407 23:27:26.995236 548067610640 worker.py:57] 'generator' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/loudml-1.6.0-py3.6.egg/loudml/worker.py", line 53, in run
    res = getattr(self, func_name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/loudml-1.6.0-py3.6.egg/loudml/worker.py", line 101, in train
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/loudml-1.6.0-py3.6.egg/loudml/donut.py", line 1091, in train
    abnormal=abnormal,
  File "/usr/local/lib/python3.6/dist-packages/loudml-1.6.0-py3.6.egg/loudml/donut.py", line 843, in _train_on_dataset
    rstate=fmin_state,
  File "/usr/local/lib/python3.6/dist-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/usr/local/lib/python3.6/dist-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/usr/local/lib/python3.6/dist-packages/hyperopt/fmin.py", line 314, in fmin
    pass_expr_memo_ctrl=pass_expr_memo_ctrl)
  File "/usr/local/lib/python3.6/dist-packages/hyperopt/base.py", line 786, in __init__
    pyll.toposort(self.expr)
  File "/usr/local/lib/python3.6/dist-packages/hyperopt/pyll/base.py", line 715, in toposort
    assert order[-1] == expr
TypeError: 'generator' object is not subscriptable
E0407 23:27:27.019252 546861736432 server.py:387] job[f9c52c44-5397-4bb9-914c-1a096e5406e6] failed: 'generator' object is not subscriptable
127.0.0.1 - - [2020-04-07 23:27:27] "GET /jobs/f9c52c44-5397-4bb9-914c-1a096e5406e6?fields=result&include_fields=false HTTP/1.1" 200 434 0.007953`

**Comment by regel** [comment]
I might have figured this out. Pull request coming before Sunday with a few optimizations.

**Comment by regel** [comment]
I'm not sure I figured out exactly what happens in count aggregations plus downsampling but unit tests seem to work now. It was hard!

Also, OpenTSDB seems to align bucket timestamps with bucket-interval multiples all the time. Good to know.

@vsergeyev Pull-request ready to be merged: https://github.com/regel/loudml/pull/263

**Comment by langerma** [comment]
i will try to test it today

**Comment by langerma** [comment]
worked :-)
