### ISSUE TITLE
loudml on mac

### ISSUE THREAD

**Issue by rohan2546** [regel/loudml#226]
Couldn't find a way to install it on mac

**Comment by simplelife2010** [comment]
Server or CLI?

Server: You could use the loudml docker image.
CLI: Works for me using pip install.

**Comment by regel** [comment]
Hey I’m a Mac user too! You’re right, I should make the installation easier for Mac users and update the documentation. There’s lots of ongoing improvement for Debian-based distros. I will do the Mac right after.

**Comment by rohan2546** [comment]
Thanks this will help. I am new to docker, so going through installation

**Comment by rohan2546** [comment]
docker run -ti -p 8077:8077 -v $VOLUME/etc/loudml/config.yml:/etc/loudml/config.yml:ro  -v $VOLUME/var/lib/loudml:/var/lib/loudml:rw loudml/loudml


Unable to find image 'loudml/loudml:latest' locally
docker: Error response from daemon: manifest for loudml/loudml:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.

what is this error
