### ISSUE TITLE
where is official Debian or RPM package?

### ISSUE THREAD

**Issue by ICDI0906** [regel/loudml#316]

**Comment by tubemeister** [comment]
Yes that.

https://loudml.io/en/loudml/reference/current/ubuntu.html

The current install page says 1.6.0 is not released yet but doesn't offer any options that are available. The 1.5 reference does have instructions for a repository but they're all 404.

**Comment by ICDI0906** [comment]
Yes, you are right. I don't know how to do it.

**Comment by tubemeister** [comment]
Me neither...

The Docker options does seem to do something, but I'd prefer to avoid Docker.

**Comment by regel** [comment]
1.6.0 is unreleased for now.

Yet, RPM files, DEB files, and Docker images are built every night. So there are options available:

- RPM install: instructions [here](https://github.com/regel/loudml/blob/develop/docs/reference/setup/install/rpm.asciidoc)
- DEB install: instructions [here](https://github.com/regel/loudml/blob/develop/docs/reference/setup/install/deb.asciidoc)
- Docker: Use `loudml/loudml:nightly` tag, instructions [here](https://hub.docker.com/r/loudml/loudml)

**Comment by regel** [comment]
Updated documentation: https://loudml.io/en/loudml/reference/current/setup.html
