### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mvadu** [regel/loudml#32]
Hi Regel,
Have you decided on the license for Loudml? Is it going to be MIT? I don't see any license added to repo.

**Comment by vnyb** [comment]
Hi,

The Python API allowing the development of extensions for LoudML is under GPL License (see https://github.com/regel/loudml/tree/master/api).

The rest of LoudML implementation distributed through `.deb`, `.rpm` and Docker image is proprietary, the source code is not published.

Regards,
Vianney

**Comment by regel** [comment]
Hi Adarsha,

there is a txt file included in the packages, and available in the Docker description: https://hub.docker.com/r/loudml/community/

These license terms are relevant to the CE (community) edition.

Please let us know your questions at contact@loudml.io if you'd like to license the EE edition, or an OEM agreement for commercial use in your application.

Best,

Sébastien
