### ISSUE TITLE
influxdb Unsupported data source

### ISSUE THREAD

**Issue by gdsmith93** [regel/loudml#33]
Hi
We've recently updated to the latest loudml and we're now receiving the following message when training/predict or forecast:

ERROR:root:Unsupported data source (type = 'influxdb')

Our datasource configuration is:

---
datasources:
 - name: influx
   type: influxdb
   addr: x.x.x.x
   database: telegraf

# - name: elastic
#   type: elasticsearch
#   addr: localhost:9200
#   index: myindex

storage:
  path: /var/lib/loudml

server:
  listen: localhost:8077

**Comment by vnyb** [comment]
Hi,

Is the `loudml-influx` package installed?

Could you please give me the result of the following commands?

```
apt-cache policy loudml-influx
```
or 
```
yum info loudml
```

and:

```
find /usr/lib -name '*loudml*'
```

**Comment by gdsmith93** [comment]
Hi

Thanks for the quick response, the outputs are below:
yum info loudml
Installed Packages
Name        : loudml
Arch        : x86_64
Version     : 1.3.2
Release     : 1.el7.centos
Size        : 172 k
Repo        : installed
From repo   : loudml-1.x
Summary     : LoudML core package
URL         : www.loudml.com
License     : Proprietary
Description :

find /usr/lib -name '*loudml*'
/usr/lib/systemd/system/loudmld.service
/usr/lib/python3.4/site-packages/loudml-1.2-py3.4.egg-info
/usr/lib/python3.4/site-packages/loudml
/usr/lib/python3.4/site-packages/loudml_influx-1.2-py3.4.egg-info
/usr/lib/python3.4/site-packages/loudml_elastic-1.3.2-py3.4.egg-info
/usr/lib/python3.4/site-packages/loudml_elastic-1.2-py3.4.egg-info
/usr/lib/python3.4/site-packages/loudml_api-1.3.0-py3.4-nspkg.pth
/usr/lib/python3.4/site-packages/loudml_api-1.3.0-py3.4.egg-info
/usr/lib/python3.4/site-packages/loudml_influx-1.3.2-py3.4-nspkg.pth
/usr/lib/python3.4/site-packages/loudml-1.3.1-py3.4.egg-info
/usr/lib/python3.4/site-packages/loudml_influx-1.3.1-py3.4.egg-info
/usr/lib/python3.4/site-packages/loudml_elastic-1.3.2-py3.4-nspkg.pth
/usr/lib/python3.4/site-packages/loudml_elastic-1.3.1-py3.4.egg-info
/usr/lib/python3.4/site-packages/loudml-1.3.2-py3.4.egg-info
/usr/lib/python3.4/site-packages/loudml_influx-1.3.2-py3.4.egg-info

Thanks

**Comment by vnyb** [comment]
It seems that old versions are not replaced. Thank's for your feedback, we currently fixing this upgrade issue.

As a workaround, you can erase the following directories:

```
/usr/lib/python3.4/site-packages/loudml-1.2-py3.4.egg-info
/usr/lib/python3.4/site-packages/loudml_influx-1.2-py3.4.egg-info
/usr/lib/python3.4/site-packages/loudml_elastic-1.2-py3.4.egg-info
/usr/lib/python3.4/site-packages/loudml-1.3.1-py3.4.egg-info
/usr/lib/python3.4/site-packages/loudml_influx-1.3.1-py3.4.egg-info
/usr/lib/python3.4/site-packages/loudml_elastic-1.3.1-py3.4.egg-info
```

**Comment by gdsmith93** [comment]
Hi, thanks for your support that worked great.
