### ISSUE TITLE
"Create baseline" button gives 404

### ISSUE THREAD

**Issue by tubemeister** [regel/loudml#340]
I'm trying to set up loudml using docker-compose and have chronograf talking to my existing influxdb, seeing proper data, so far so good.

But when I make a query and click the "Create baseline" button, I get a 404:

chronograf_1  | time="2020-06-18T16:01:45Z" level=info msg="Response: Not Found" component=server method=POST remote_addr="x.x.x.x:47772" response_time=1.759522ms status=404

Any idea what's going wrong?

Screenshot of the "Create baseline" button:
![mouseover](https://user-images.githubusercontent.com/91840/85045984-0e354300-b190-11ea-9d42-8719c02251cf.png)

Config files:
[loudml.yml.txt](https://github.com/regel/loudml/files/4799811/loudml.yml.txt)
[docker-compose.yml.txt](https://github.com/regel/loudml/files/4799812/docker-compose.yml.txt)

Docker log:
[log.txt](https://github.com/regel/loudml/files/4799810/log.txt)

**Comment by regel** [comment]
You can switch to `loudml/loudml:nightly` image and tag, this is the latest. If needed, compare docker-compose file with the version available in 'develop' branch.

**Comment by tubemeister** [comment]
So the stable release is just broken?

**Comment by regel** [comment]
To get started: checkout or update develop or master (stable) branch, `cd docker/compose`, then edit the image line and use tag 1.6.0 (stable, tagged 48 hours ago):

`image: loudml/loudml:1.6.0`

Finally, run:

```
docker-compose pull
docker-compose up
```

The forked Chronograf docker image has a single tag: `latest` ; there is still a lot of work to do in this React application. One alternative is the Grafana plugin, maintained by @vsergeyev  - I don't know if the docker image is available or if it's work in progress.

**Comment by vsergeyev** [comment]
Grafana loudml plugin:


  docker run -d \
  -p 3000:3000 \
  --name=grafana \
  -e "GF_INSTALL_PLUGINS=https://github.com/vsergeyev/loudml-grafana-app/raw/master/loudml-grafana-app-1.4.0.zip;loudml-grafana-app" \
  grafana/grafana

**Comment by vsergeyev** [comment]
previous example is for Grafana 6.x
for latest 7.x please use 

  docker run -d \
  -p 3000:3000 \
  --name=grafana \
  -e "GF_INSTALL_PLUGINS=https://github.com/vsergeyev/loudml-grafana-app/raw/master/loudml-grafana-app-1.4.0-grafana7.zip;loudml-grafana-app" \
  grafana/grafana

Please post any bugs on https://github.com/vsergeyev/loudml-grafana-app

@regel thank you for mentioning me :)

V.

**Comment by tubemeister** [comment]
Loudml 1.6.0 seems to fix this 404 issue, onto the next issue! ;-) 

Loudml seems to connect to influxdb with the env settings given to the chronograf container, stripping off the https somewhere in between. I'll make a new issue for that, to keep things clear.

vsergeyev, I'll have a look at that plugin once I've got loudml running, looks interesting.
