### ISSUE TITLE
Tag anomalies in the prediction_* measurement

### ISSUE THREAD

**Issue by jorgelbg** [regel/loudml#39]
At the moment when the result prediction is stored, on InfluxDB we only have access to the `time` and the output features. I think that adding a tag for when one of this predicted data points is an anomaly can be useful for:

* Visualizing the anomalies in Grafana/Chronograf 
* Using a third party alerting mechanism

**Comment by regel** [comment]
Hi Jorge,

You've read our minds!

We will tag the output predictions with is_anomaly=True|False. This change will be included in 1.4.0, due in just a couple days. A brief tutorial and example for live anomaly detection will be available on Youtube too. You can subscribe to our Twitter channel @loud_ml to receive the announcement ;)

Best,
Sébastien

**Comment by regel** [comment]
Tagging predictions implemented in release 1.4.0, will be released in the next couple days.

**Comment by regel** [comment]
Fixed in 1.4.0, release notes: http://loudml.io/guide/en/loudml/reference/current/release-notes-1.4.0.html

Thanks for your support!
