### ISSUE TITLE
Invalid field error when a dot is used in the measurement key of the model

### ISSUE THREAD

**Issue by jorgelbg** [regel/loudml#40]
With the current configuration in the feature

```json
  "features": {
    "io": [{
      "default": 0,
      "metric": "mean",
      "field": "value-derive",
      "measurement": "clicks.on_title",
      "name": "avg_clickouts",
      "anomaly_type": "low",
      ...
   }]
```

I get the following error when creating the model:

```
ERROR:root:invalid field features.i.0.measurement: not a valid value
```

Granted this is coming from a legacy application that is using the graphite naming format 😄 but It should not be a problem for LoudML.

**Comment by regel** [comment]
@jorgelbg : Very good point. 1.4.2 was released today. Dots are now allowed in fields, but not measurement names :( We will have to make a 1.4.3 in order to allow the dots in measurements names. Work in progress.

**Comment by jorgelbg** [comment]
👍Thanks, @regel I've tested this today again, and the model is created successfully.
