### ISSUE TITLE
Bad magic number on startup

### ISSUE THREAD

**Issue by mrb1090** [regel/loudml#41]
Just installed loudml per documentation on Ubuntu 16.04, Python 3.5.2.
Getting the following error when trying to start the daemon under system:

Sep 06 13:18:46 INFLX loudmld[1526]: ImportError: bad magic number in 'loudml.server': b'\x17\r\r\n'
Sep 06 13:18:46 INFLX systemd[1]: loudmld.service: Main process exited, code=exited, status=1/FAILURE
Sep 06 13:18:46 INFLX systemd[1]: loudmld.service: Unit entered failed state.
Sep 06 13:18:46 INFLX systemd[1]: loudmld.service: Failed with result 'exit-code'.

Any suggestions resolving this error would be much appreciated.

Mike B.

**Comment by osunac** [comment]
Thanks for using LoudML.

The deb package is designed to run on Debian 9 (Stretch) 64 bits. We will try to expand the list of supported targets in the future, but currently Debian 9 is mandatory for that package format.

Is it acceptable for you to use another operating system?

**Comment by regel** [comment]
@mrb1090 Hi Mike, we're updating today the documentation, with a new release (1.4.2). It is now compatible with Debian 9, and Ubuntu 18.04.

**Comment by ankur-gupta619** [comment]
Hi,
I am getting the below error while starting the loudmld service:

```
Oct 06 07:25:25 systemd[1]: Stopped LoudML daemon.
Oct 06 07:25:25 systemd[1]: Started LoudML daemon.
Oct 06 07:25:26 loudmld[72562]: Traceback (most recent call last):
Oct 06 07:25:26 loudmld[72562]:   File "/usr/bin/loudmld", line 11, in <module>
Oct 06 07:25:26 loudmld[72562]:     load_entry_point('loudml==1.4', 'console_scripts', 'loudmld')()
Oct 06 07:25:26 loudmld[72562]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
Oct 06 07:25:26 loudmld[72562]:     return get_distribution(dist).load_entry_point(group, name)
Oct 06 07:25:26 loudmld[72562]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
Oct 06 07:25:26 loudmld[72562]:     return ep.load()
Oct 06 07:25:26 loudmld[72562]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
Oct 06 07:25:26 loudmld[72562]:     return self.resolve()
Oct 06 07:25:26 loudmld[72562]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
Oct 06 07:25:26 loudmld[72562]:     module = __import__(self.module_name, fromlist=['__name__'], level=0)
Oct 06 07:25:26 loudmld[72562]: ImportError: bad magic number in 'loudml.server': b'3\r\r\n'
Oct 06 07:25:26 systemd[1]: loudmld.service: Main process exited, code=exited, status=1/FAILURE
Oct 06 07:25:26 systemd[1]: loudmld.service: Unit entered failed state.
Oct 06 07:25:26 systemd[1]: loudmld.service: Failed with result 'exit-code'.
Oct 06 07:25:26 systemd[1]: loudmld.service: Service hold-off time over, scheduling restart.
Oct 06 07:25:26 systemd[1]: Stopped LoudML daemon.
Oct 06 07:25:26 systemd[1]: loudmld.service: Start request repeated too quickly.
Oct 06 07:25:26 systemd[1]: Failed to start LoudML daemon.
```

I am using Ubuntu 16.04 and Python 3.5.2. 
I also tried the docker setup but that was also hanging while starting the container. 

Can you please help me resolving this issue?

**Comment by osunac** [comment]
Hi. The packages are only for Ubuntu 18.04. Currently we do not have packages for Ubuntu 16.04.

The Docker container should work. The instructions on how to start the container are available at [https://hub.docker.com/r/loudml/community/]. Also, I have experienced issues when SELinux is enabled. If `getenforce` tells you SELinux is enabled, try to set it to permissive mode with `setenforce permissive`. If the problem persists, could you open a separate ticket (to make it more visible to the other users who may experience similar issue)?
