### ISSUE TITLE
LoudML 1.4 doesn't use the measurement field when used with ES

### ISSUE THREAD

**Issue by jorgelbg** [regel/loudml#42]
In our case, we've several ES indexes with a `_type` set to `logs`. 

Setting the measurement to `logs` in the model definition, it doesn't have any impact on the request sent to ES:

In the model definition:

```
    "bucket_interval": "5m",
    "default_datasource": "elastic",
    "timestamp_field": "@timestamp",
    "features": [
      {
        "default": 0,
        "metric": "max",
        "field": "error_count",
        "measurement": "logs",
        "name": "count_errors",
        "anomaly_type": "low_high",
        "match_all": [
          {"tag": "partner_id", "value": "1234"}
        ]
      }
    ],
```

Inspecting the traffic with tcpdump on port 9200:

```
GET /errorratio*/doc/_search?size=0 HTTP/1.1
Host: 10.1.3.100:9200
Accept-Encoding: identity
Content-Length: 443
content-type: application/json
connection: keep-alive
....
```

Although multiple document types in the same index are deprecated it is still possible to have only one that is not `doc`.

**Comment by jorgelbg** [comment]
Using LoudML 1.3, something similar happens, but it works because it doesn't default to `doc`:

```
GET /errorratio*/_search?size=0 HTTP/1.1
Host: 10.1.3.100:9200
Accept-Encoding: identity
Content-Length: 358
connection: keep-alive
content-type: application/json
```

**Comment by regel** [comment]
Hi Jorge,

Thanks a lot for sharing the issue. If our understanding is correct, ES 6.x will only allow one doc_type value with a given index. Can we define a 'doc_type' parameter at the top level in config.yml data source definition? It will avoid repetitions, do you think it will work for you?

We're code complete with 1.4.1 tomorrow. Let us know your comments, we will try to make a quick fix if we can before the release.

Best,
Sébastien

**Comment by jorgelbg** [comment]
@regel I think that the best option would be, as you say, specifying a `doc_type` parameter on the `config.yml`. There is already a 1 index = 1 doc_type, so this makes perfect sense.

Thanks for the quick reply!

**Comment by regel** [comment]
@jorgelbg : 1.4.2 has just been released today, and the documentation updated. You can set the doc_type in your config.yml file. Waiting for your confirmation to close this issue.

**Comment by jorgelbg** [comment]
Hi @regel sorry for the super-delayed response 😅. 
I've tried the new version against our production ES cluster and its working perfectly. I'm able to train the model, and store the predictions back to ES.

On the documentation would be helpful to specify that the predictions on ES are going to be stored in an index matching the name of the model. 
On InfluxDB is a bit different, the name follows the `prediction_model_name` which could cause a bit of confusion. I would be happy to open a new issue if it helps. 

Thanks for the great work!
