### ISSUE TITLE
Example docker-compose file?

### ISSUE THREAD

**Issue by jgentes** [regel/loudml#43]
Hey guys, interested in learning more about LoudML. [The documentation](http://loudml.io/guide/en/loudml/reference/current/docker.html) talks about a sample docker-compose file in a docker-compose directory in the LoudML repo, but I can't seem to find it. Any pointers?

**Comment by jgentes** [comment]
I think I found it: https://github.com/lmangani/loudml-docker/blob/master/docker-compose.yml

**Comment by osunac** [comment]
Actually it looks like our sample Dockerfile is not online. The one that you found does work, but is slightly different from the one we intended to suggest as a starting point.

**Comment by jgentes** [comment]
Thanks, would be great to see your version. The other one has a dependency on elasticsearch that I didn't notice before.

**Comment by regel** [comment]
@jgentes New Docker compose file has been published in the repo. This spins up the full TICK-L stack, please let us know your feedback:

https://github.com/regel/loudml/tree/master/docker
