### ISSUE TITLE
detect_anomalies and save_prediction not documented

### ISSUE THREAD

**Issue by daradermody** [regel/loudml#45]
`detect_anomalies` and `save_prediction` parameters are not described in the [activate API documentation](http://loudml.io/guide/en/loudml/reference/1.4/_activate_model_api.html). It took me a while to figure out that these are required for what I though was default behaviour (because it says "the predicted values will automatically be written to your data source").

`detect_anomalies` is only referred to in the [Putting it all Together section](http://loudml.io/guide/en/loudml/reference/1.4/_putting_it_all_together_an_email_notification_example.html) in the Hooks API

**Comment by regel** [comment]
You may need to clear your navigator's cache, the documentation is now up to date with a couple more fixes. Thanks again for reporting this.
