### ISSUE TITLE
No documentation for fingerprint model type

### ISSUE THREAD

**Issue by daradermody** [regel/loudml#47]
In the [Create Model](http://loudml.io/guide/en/loudml/reference/1.4/cli-create-model.html) section of the documentation, it mentions that the model type can be `timeseries` or `fingerprint`. I can't see anywhere where it describes what the `fingerprint` type is. Is this the same as `population` [in X-pack](https://www.elastic.co/guide/en/x-pack/current/ml-configuring-pop.html)?.

**Comment by regel** [comment]
The fingerprint model type was removed in 1.5, we will replace it with a better implementation in a future release.
