### ISSUE TITLE
Periodically delete old jobs

### ISSUE THREAD

**Issue by daradermody** [regel/loudml#51]
I left Loud ML running for about a week, and when I called the `/jobs` API, it came back with more than 2826 jobs, most of type `prediction` (that's all the JSON that could fit in my terminal scrollback buffer). There were probably a few thousand more because the earliest job I could see was from about day and a half ago. I think there should be some cleanup done for old jobs, maybe something configurable from the `config.yml` file.

**Comment by regel** [comment]
Hi @daradermody, good point, thanks. @vnyb what setting could be added to `config.yml` file?

**Comment by regel** [comment]
How about a new `maxjobs` param in config.yml:

```
server:
  listen: 0.0.0.0:8077
  maxjobs: 128
```
