### ISSUE TITLE
Give timestamp in job information

### ISSUE THREAD

**Issue by daradermody** [regel/loudml#55]
Jobs returned by the `/jobs` API don't have any time information associated with them. I don't know if start time or end time would be better, but I'd like something to be able to order them or know which ones are important (e.g. have been run recently).

Duration might be good to see too, as it would give me good metrics for performance based on the model parameters I used.

**Comment by vnyb** [comment]
Indeed. `NaN` values will be replaced with `null`

**Comment by vnyb** [comment]
We'll add following fields in job status:

`"start_time": "YYYY-MM-DDTHH:mm:ss.sss"`

When job is over:
`"end_time": "YYYY-MM-DDTHH:mm:ss.sss"` 
`"duration": seconds`

When job running:

`"remaining_time": seconds`
(estimation)

**Comment by regel** [comment]
@daradermody do you confirm this works for you if we target 1.4.4?

**Comment by regel** [comment]
Hi @daradermody feel free to submit a pull request. It's a good first issue to learn the Job runner implementation. Useful info: see the progress_cb callback.
