### ISSUE TITLE
Specify output index during model creation

### ISSUE THREAD

**Issue by daradermody** [regel/loudml#58]
Feature request: Add ability to specify the output index (where predictions are saved) during model creation, instead of just using the model name.

**Comment by regel** [comment]
Hi @daradermody, we're about to roll out 1.4.3 in the next days or so. We've made progress to include a "datasink" parameter, so in practice this allows to output and write data points to a separate data source that we call a sink.

@vnyb can we document a short example of datasink usage with Elasticsearch? @daradermody can you let us know your comments on this before 1.4.3 is out?

**Comment by daradermody** [comment]
By "datasink", do you mean being able to specify separate output indices for each model, or choose a single output index for all models (maybe delimited by a term field that mentions the model name)? We would prefer the latter as it would be easier to manage. The former can work for us as well, though.

**Comment by regel** [comment]
Hi @daradermody, both, changes that we plan to introduce in 1.4.3:
 - You can write "default_datasink": "_name_" in your JSON file when creating the model. _name_ is declared in your config.yml
 - All points written to output indices include a keyword term, named "model" to include the model name, if you store everything in one global index it's still possible to find the data quickly

A query on the output index, will return eg:

```
            {
                "_id": "tvgDy2YBoTOdX_e1s6P-",
                "_index": "bar-2018.10.31",
                "_score": 1.0,
                "_source": {
                    "count_val": 704.65771484375,
                    "is_anomaly": false,
                    "lower_count_val": 694.2425824418498,
                    "model": "timeseries1",
                    "my_tag": "1",
                    "score": 0.3188325786817048,
                    "timestamp": 1540990350000,
                    "upper_count_val": 709.0
                },
                "_type": "doc"
            },
```

Let us know if it works for you

**Comment by daradermody** [comment]
That'll work like a charm :+1:

**Comment by regel** [comment]
Hi @daradermody , reading from the other entries 1.4.3 is close to your expectations, and https://github.com/regel/loudml/issues/74 and https://github.com/regel/loudml/issues/76 can be tracked separately.

Am I missing something, or can we close this one?

**Comment by daradermody** [comment]
Yes, you can close as 1.4.3 is providing me what I wanted, thanks.
