### ISSUE TITLE
Question: Model evolution

### ISSUE THREAD

**Issue by daradermody** [regel/loudml#59]
I was wondering if the model created and trained evolves if the pattern of data slowly changes? Or is the model only based off of the last training session. If it evolves, is there a specific behaviour, like does it train every time it does a prediction, or do a bigger training session every larger period, etc.?

**Comment by regel** [comment]
Hi @daradermody, I have published 1.5 roadmap on [slideshare](https://www.slideshare.net/SebastienLeger1/loud-ml-15-technology-roadmap).

You will find incremental retraining, and how 1.4 compares to the next 1.5 on this question.

**Comment by daradermody** [comment]
Thanks for the slideshare. Keeps me looking forward to the new features :smile:

**Comment by regel** [comment]
EXPERIMENTAL: a crontab definition and incremental training support have been added to 1.5.0 - this new feature still requires additional unit tests. Using the crontab py module does not work in virtual env, a better option would be to use the py schedule module.

**Comment by regel** [comment]
Solved by scheduled_jobs on master (future 1.6.0 release)
