### ISSUE TITLE
Model name requirements not clear

### ISSUE THREAD

**Issue by daradermody** [regel/loudml#62]
If I try to create a model with a name with spaces, it gives me the following error:
```
model_name is invalid: does not match regular expression
```
I can understand why spaces wouldn't be allowed, but I'd like some clarification on what else is invalid (e..g what regex is applied to the name?)

**Comment by regel** [comment]
Hi @daradermody, ok thanks. @vnyb can you please comment the current format accepted. We definitely have to update the documentation.

**Comment by vnyb** [comment]
Hi @daradermody, the regexp is `^[a-zA-Z0-9-_@]+$`. Documentation will be updated and we'll add this information in the error message.

**Comment by regel** [comment]
Documentation updated
