### ISSUE TITLE
Actual value in prediction output

### ISSUE THREAD

**Issue by daradermody** [regel/loudml#67]
The output of a prediction job contains the real value found
```javascript
{
  "id": "1e159e46-080c-4846-bc13-25ebfe66aba2",
  "result": {
    "observed": {
      "value": [
        -0.7891841530799866,
        -0.7149271368980408,
        ...
      ]
    },
  ...
}
```
But when pushed to Elasticsearch, it is missing:
```json
{
  "upper_value": 0.021351980635097245,
  "score": 1.9360708411284344,
  "@timestamp": 1540901398000,
  "is_anomaly": false,
  "lower_value": -0.2516915077652242,
  "value": -0.11516976356506348
}
```

Because it's difficult to be able to replicate the query used by Loud ML and determine the real value used in the anomaly detection, I was wondering if the actual value could be included in the prediction result pushed to Elasticsearch?

**Comment by vnyb** [comment]
Of course! It will be added to Loud ML 1.4.4. Thanks!

**Comment by regel** [comment]
@daradermody this one is a good first issue, feel free to submit a pull request. All plugins implement the datasource.py interface, you will probably have to change the save() function.

**Comment by regel** [comment]
Solved on master.
