### ISSUE TITLE
Bucket interval doesn't support 'M' or 'y' date math units

### ISSUE THREAD

**Issue by daradermody** [regel/loudml#68]
I expected that all [Elasticsearch date math units](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#date-math) would be supported, but using either `M` or `y` (e.g. `"bucket_interval": "1M"`) results in an error:
```
"data is invalid: invalid time delta"
```

**Comment by regel** [comment]
fixed in 1.5.0
