### ISSUE TITLE
Your email is broken

### ISSUE THREAD

**Issue by camAtGitHub** [regel/loudml#69]
Hi LoudML.
Firstly I tried to email contact@loudml.com AND contact@loudml.io (as per your website) and got the following bounce back:

> Hello [redacted],

We're writing to let you know that the group you tried to contact (contact) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/loudml.io/bin/topic.py?topic=25838.

Thanks,

loudml.io admins

**Comment by wendyhollands** [comment]
Thanks for letting us know. The issue has now been resolved and you're welcome to write to us at contact@loudml.io now that we'll receive your message.

**Comment by camAtGitHub** [comment]
Presuming its fixed ill close this
