### ISSUE TITLE
Consider using a default of 4 shards for datasink indexes

### ISSUE THREAD

**Issue by daradermody** [regel/loudml#77]
When creating datasink indexes, Loud ML doesn't specify the shards, so Elasticsearch uses the default 5 shards. Would it be possible to default to 4 so that, if needed, it is easier to pack them to 2 or 1 shard without reindexing (using the [Shrink Index API](https://www.elastic.co/guide/en/elasticsearch/reference/6.x/indices-shrink-index.html#indices-shrink-index))?

**Comment by regel** [comment]
@daradermody a good first issue to submit a PR, see elastic.py source code.

**Comment by regel** [comment]
Waiting for pull-request [145](https://github.com/regel/loudml/pull/145) to be merged.

**Comment by regel** [comment]
Solved on master (future 1.6.0 release). Settings can be defined at the bucket level.
