### ISSUE TITLE
Connection refus with InfluxDB.

### ISSUE THREAD

**Issue by patelnikhilg** [regel/loudml#78]
Telegraf is not able to connect with InfluxDB. below error is getting:

telegraf_1_d30ed5f852c7 | 2018-11-19T13:16:20Z E! Error writing to output [influxdb]: could not write any address
telegraf_1_d30ed5f852c7 | 2018-11-19T13:16:30Z E! [outputs.influxdb] when writing to [http://localhost:8086]: Post http://localhost:8086/write?db=telegraf: dial tcp 127.0.0.1:8086: connect: connection refused

Kapacitor is not able to connect with InfluxDB. below error is getting:

kapacitor_1_54567c41aaf9 | ts=2018-11-19T13:21:19.641Z lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="Get http://localhost:8086/ping: dial tcp 127.0.0.1:8086: connect: connection refused"

**Comment by osunac** [comment]
Hi.

Are you using Docker Compose with our [Dockerfile](https://github.com/regel/loudml/tree/master/docker)? The URLs in that file should be left untouched because they are designed to point to the containers spawned by Docker Compose.

If you still have issues, could you check that:
1. SELinux is disabled (see FAQ);
2. you have a recent version of Docker and Docker Compose?

**Comment by patelnikhilg** [comment]
> 1. see FAQ
SELINUX=disabled
I have docker Compose version link : https://github.com/regel/loudml/tree/master/docker

**Comment by osunac** [comment]
I am unable to reproduce the issue, so I guess this is related to the environment.

The container names should be resolved to IP addresses, not to `localhost`. My guess is that Docker Compose is reusing resources from a previous run. Could you try to:
1. stop all Loud ML related containers (probably already the case)
2. remove all unused Docker resources with `docker system prune` (or at least `docker network prune` if the previous command seems too dangerous)
3. try again to run the TICK-L stack with `docker-compose up` (and other instructions from the README)

If you still have issues, I think it would be interesting to see how the environment variables defined in `docker-compose.yml` are handled in the containers. Below is an example of the expected output:

```
$ docker-compose exec telegraf /bin/bash
root@4852cd530e55:/# echo $INFLUXDB_URL
http://influxdb:8086
```
