### ISSUE TITLE
DEB packages missing

### ISSUE THREAD

**Issue by lmangani** [regel/loudml#8]
Hi Sebastien,

Following the setup instructions, the DEB package repository location seems to be non existing:
```
  http://loudml.s3-website-eu-west-1.amazonaws.com/repo/deb/pool/main/l/loudml/loudml_1.2.0_all.deb
...
HTTP request sent, awaiting response... 404 Not Found
2018-02-28 00:40:32 ERROR 404: Not Found.
```

Any advice or suggestions?

**Comment by osunac** [comment]
The version in the repository is 1.2.0 plus some patches, resulting in the version number to be different.

I recommend following the documentation at http://loudml.io/guide/en/loudml/reference/current/deb.html :
- install dependencies
- create a file ` /etc/apt/sources.list.d/loudml-1.x.list` with the following contents:
```
deb http://loudml.s3-website-eu-west-1.amazonaws.com/repo/deb/ stretch main
```
- run the commands to install the packages
```
apt-get update
apt-get install loudml loudml-elastic loudml-influx
```
- (skip the section about manual install)
- configure `systemd`

At that point you should be good.

**Comment by regel** [comment]
It should be solved now with 1.2.1, is it ? Thank you Lorenzo for downloading the package. Please let us know your thoughts&ideas on what's missing in this release;)

**Comment by lmangani** [comment]
Thanks! We're playing with it and will sure have feedback soon, thanks for sharing!

**Comment by opvizordz** [comment]
1.2.1 manual installation works well! Thanks
