### ISSUE TITLE
How to stop training?

### ISSUE THREAD

**Issue by sergibondarenko** [regel/loudml#80]
It is possible to start [trainings](https://loudml.io/guide/en/loudml/reference/current/_train_model_api.html). Is it possible to stop or pause the training in progress?

**Comment by vnyb** [comment]
Hi,

You can cancel any job by sending a `DELETE` query on `/jobs/<job_id>` endpoint.

You can retrieve the ID of training job using `GET` on `/models/<model_name>`, then cancel the job using `DELETE` on `/jobs/<job_id>`:

Example:

`curl http://localhost:8077/models/my-model`

```
{
  ...
  "training": {
    "job_id": "a333c42e-5bca-485f-afe4-3878d24a8cca",
    "progress": { "eval": 10, "max_evals": 100 },
    "state": "running"
  }
}
```
`curl -X DELETE http://localhost:8077/jobs/a333c42e-5bca-485f-afe4-3878d24a8cca`

**Comment by regel** [comment]
@sergibondarenko 

Hi Sergii, if your max_evals is equal to 100 it can be quite long. You can change this value if needed, it's not well documented though but you can use POST to overwrite a given model settings.

How many data points / time-window in your training data-set?

Is everything clear with regard to the DELETE API call?

**Comment by sergibondarenko** [comment]
@regel yes, everything is clear, thank you.
