### ISSUE TITLE
forecast fails with no data found

### ISSUE THREAD

**Issue by sukotha** [regel/loudml#85]
when we use forecast command like below, it errors out saying that no data is found for the time range.
loudml forecast --from "now" --to "now+1d" TEST_MODEL

ERROR:root:no data found for time range 2019-01-28T19:15:00.000Z-2019-01-29T20:10:00.000Z

**Comment by regel** [comment]
A sliding window (span) is used to forecast. So, if the --from parameter is "now", then loudml is querying the data source to load the window with data points in range [now-span*bucket_interval, now[

This first window must not have any missing data point, else the forecast will not be able to produce an output.

Tips and workarounds:

- Use --from "now-1m" or small negative offset to ensure the first window does not have "null" data points
- Control the bucket_interval in model settings, and verify if the buckets are empty (any warnings observed on the CLI)
- Use default: "previous", or default: <float> in your feature definition to assign a default value in case there are no previous data point in the TSDB

Our next release 1.5 will have much more advanced forecast functions. Let us know how this can help your business to join the beta and 1.5 early access crew.

**Comment by regel** [comment]
@sukotha : closing this question. Please check out the 1.5 OSS release. Changes are documented in the release notes.
