### ISSUE TITLE
OpenTSDB data source

### ISSUE THREAD

**Issue by regel** [regel/loudml#91]
Your help is wanted to release the OpenTSDB data source plugin in the next Loud ML release. Please check the contributing guide, and refer to datasource.py and influxdb.py for a reference data source implementation.

**Comment by langerma** [comment]
I have a small library for dealing with opentsdb (https://github.com/langerma/py-opentsdb) as the code of this whole project is really complex...i am not sure if i can integrate it.

**Comment by regel** [comment]
Hi, it's a great start! Happy to find a new contributor :)

I will help, don't worry. 

Refactoring is ongoing on the master branch. It will make things easier (I hope!). The "Datasource" class will be renamed "Bucket".

The basic requirements to make it work:

1. Write `loudml/loudml/opentsdb.py` file with a class inherited from the parent Bucket class, then declare this class in setup.py. Your class must implement __init__(), init(), drop(), insert_times_data(), and get_times_data(). You can have a SCHEMA class variable used to declare and validate the config.yml file format. Examples in influx.py. This file mainly builds date histogram aggregations in the format expected by the TSDB, runs the query, and returns data and timestamps. The `misc.py` file contains helpers to work with timestamps.
2. Please avoid pandas. We want to keep it simple and avoid extra dependencies. It's better if everything is contained in one file.
3. Write a unit test file `loudml/tests/test_opentsdb.py`. You can copy/paste most of the content from `test_elastic.py` or `test_influx.py`
4. Update the `.circleci/config.yml` to test with OpenTSDB latest version. It should be a copy/paste of the existing configuration for other TSDBs.
5. Last but not least, add your name in the Contributors section of the top README file!

I review new pull-requests with @osunac 

Let us know if you have questions or get stuck on something. I will let you know when the Bucket refactoring is completed and merged on `master`.

We know OpenTSDB users who will be happy to test a new release.

**Comment by langerma** [comment]
cool! i'll have a try next week :-)

**Comment by regel** [comment]
@langerma 

You can get a sneak peek of what's coming in the next release by checking out the `enhance_apis` branch and this [PR](https://github.com/regel/loudml/pull/145) (not merged yet).

Refactoring of the `Bucket` class is completed. This is the new name for the old 'Data Source' class. Elastic, and other TSDB implementation should be a lot more readable too.

Extra documentation was just added:  `git show 073e2a6d323cfec2126863b997a82ebeeed47b01`

Hope this helps. I guess it's easier to work in this new branch since it's the most up to date, and rebase on master later on.

Let me know your comments, always happy to receive feedback!

Ps: I won't be available for the next few days.

**Comment by regel** [comment]
It’s here. The changes have been merged on master, documentation updated, and the loudml client CLI moved to a separate lib (loudml-python) that users can find and install using PyPI.

You want to look at the Bucket class. Let me know your comments and questions.
